version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /terraform/test
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
    groups:
      terraform-providers:
        patterns:
          - "*"
