---
APPLY_FIXES: all
ENABLE_LINTERS:
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_FMT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - YAML_YAMLLINT
  - ACTION_ACTIONLINT
  - KUBERNETES_HELM
  - MARKDOWN_MARKDOWNLINT
TERRAFORM_TFLINT_CONFIG_FILE: terraform/.tflint.hcl
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
