name: Renovate
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: renovatebot/github-action@757597d1bb6993c6406e207997a85f2b20ff39be # v41.0.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          RENOVATE_BASE_BRANCHES: ${{ github.event_name == 'pull_request' && github.head_ref || '' }}
